version: '2'

services:
    catalogue-db:
        build:
            context: ./docker/catalogue-db/
        image: mysql:5.7
        restart: always
        environment:
 #           - reschedule=on-node-failure
 #           - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
 #           - MYSQL_ALLOW_EMPTY_PASSWORD=true
 #           - MYSQL_DATABASE=socksdb
               MYSQL_DATABASE: 'socksdb'
               MYSQL_USER: 'user'
               MYSQL_PASSWORD: 'password'
               MYSQL_ROOT_PASSWORD: 'password'
 #       volumes:
 #           - ./database:/socksdb
        ports:
         - "3306:3306"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:3306"]
            interval: 30s
            timeout: 10s
            retries: 5
    catalogue:
     build:
            context: .
            dockerfile: ./Dockerfile
     image: arijmansour/pfe_catalogue_microservice:latest
     depends_on:
      catalogue-db:
        condition: service_healthy
     hostname: pfe_catalogue_microservice
     restart: always
     ports:
      - "80:80"
    
    


